name = "sim-ppds-cloudflare"
pages_build_output_dir = ".open-next"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "sim-ppds-db-v2"
database_id = "27ec7392-6ac2-4bdc-8570-69ab4057e485"
