name = "sim-ppds-cloudflare"
compatibility_date = "2024-01-01"
# For Next.js on Cloudflare Pages
pages_build_output_dir = ".vercel/output/static"
compatibility_flags = ["nodejs_compat"]

[vars]
# Add your environment variables here

[[d1_databases]]
binding = "DB"
database_name = "sim-ppds-db-v2"
database_id = "27ec7392-6ac2-4bdc-8570-69ab4057e485"
