name = "sim-ppds-cloudflare"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"
compatibility_flags = ["nodejs_compat"]

[vars]
# Add your environment variables here or in Cloudflare Dashboard
# DATABASE_URL = "..."
# CLOUDINARY_CLOUD_NAME = "..."
# CLOUDINARY_API_KEY = "..."
# CLOUDINARY_API_SECRET = "..."

[[d1_databases]]
binding = "DB"
database_name = "sim-ppds-db"
database_id = "b6c86bc4-4c50-4256-97c2-463ab8dab602"
